# ------ root_path/dataset_name ------
root_path: '/newdisk2/oyx/ILSVRC/Data/CLS-LOC/'


# ------ Load Cache and Features ------
# load_cache: False
# load_pre_feat: False

load_cache: True
load_pre_feat: True


# ------ knn datastore  ------
# knn_mode: True
knn_mode: False
topk: 8


# ------ Hyperparamters ------
search_hp: True
# search_hp: False

search_scale: [7, 3, 5]
search_step: [80, 20, 40]

init_beta: 1
init_alpha: 1.17
init_gamma: 1


# ------ Basic Config ------
dataset: 'imagenet'
shots: 16
backbone: 'RN50'

lr: 0.001
augment_epoch: 10
train_epoch: 20